---
title: "Mihir Project Milestone 3 Separate Work"
output: html_document
date: "2023-11-04"
---

Vaccination dataset 

    -   Recode values to be consistent with morbidity datasets so they can be joined

    -   Select vaccination time frame that fits best with morbidity data and subset appropriately

    -   Select demographic strata(s) of interest

    -   Create a vaccination rate metric and summarize to include only one row per strata of interest

```{r}
# Adding all the packages that is necessary for the cleaning and importing done in this milestone, using readr, tidyverse, dplyr

library(readr)
library(tidyverse)
library(dplyr)
```

```{r}
# Importing the vaccination dataset

ca_vax <- read_csv("./ca_vax_rates_quarter.csv")
View(ca_vax)
```

```{r}
# Recoding the column names to match morbidity datasets to ready them to join
ca_vax_renamed <- rename_with(ca_vax,
                      ~ tolower(
                        gsub(" ",
                             "_",
                             .x,
                             fixed = TRUE)
                      ))
```

```{r}
# Selecting a time frame that matches the morbidity dataset and subset

ca_vax_time_frame <- subset(ca_vax_renamed, quarter == "2023-04-01")
```

```{r}
# Selecting demographic strata of interest

ca_demographics <- subset(ca_vax_time_frame, demographic_category == "Age Group")
```

```{r}
# Creating vaccination rate metric

ca_metric <- mutate(
  ca_demographics,
  "vaccination_rate" = (ca_demographics$cumulative_fully_vaccinated / ca_demographics$estimated_population) * 100)
```