---
title: "Mihir Project Milestone 6 (Final Submission) Separate Work"
output: html_document
date: "2023-12-05"
---

Problem:

In recent years, given the pandemic of COVID-19, vaccination rates have risen since the introduction of COVID-19 vaccines at the end of calendar year 2020. This is true for the state of California, where vaccination data across all of the states 58 counties (stratified by age) can be used for infectious diseases surveillance by the California Department of Public Health. Specifically, analysis of the aforementioned data could reveal if COVID-19 vaccination rates have any impact on flu vaccination rates. This can be done by examining data for flu cases and severity across the entire state stratified by demographic categories (age/race/sex), including in the states largest county, Los Angeles.

Methods:

The three aforementioned data sources used as the basis for this analysis between COVID-19 vaccination rates and those for the flu are the following: weekly data for flu cases and severity by demographic (age/race/sex) categories across all California counties except Los Angeles (sim_flu_CA.csv), similar data as sim_flu_CA.csv except just for Los Angeles County (sim_flu_LACounty.csv), and quarterly COVID-19 vaccination data by age for all of California's 58 counties (ca_vax_rates_quarter.csv). Both the sim_flu_CA.csv and sim_flu_LACounty.csv span the entirety of calendar year 2022 and calendar year 2023. ca_vax_rates_quarter.csv includes that and starts as far back as the third quarter of calendar year 2020. All three of these were read in to begin the data analysis process.

Both of the flu datasets were then cleaned in order to facilitate a final merger. This was done by renaming the columns to a snakecase format, standardizing the column names themselves (sim_flu_LACounty.csv columns were renamed and a column was added to match sim_flu_CA.csv). The data types and associated formatting were then standardized (like for date values). Both datasets were then merged once they were fully aligned/ready. This combined dataset was then subset to include only data for Alameda County and age, the characteristics of interest for data analysis. This combined dataset was then summarized into mean and cumulative columns, using the mean() and last() functions, respectively.

The COVID-19 vaccination data was then cleaned in order facilitate eventually joining it with the flu morbidity data. The columns were renamed to a snakecase format, subset to include data from the second quarter of calendar year 2023 only, and then further subset to include only data for Alameda County and age, and subset a final time to account for only one stratification of age (merging three ranges within 0-17 to just 0-17) into a single row (summary() function). The vaccination rate was then calculated in a separate column. After this, the dataset was combined with the flu morbidity dataset, and there was some minor column renaming/arrangement after. Descriptive statistics of this combined dataset were generated and presented in table format.