---
title: 'W251 Project Milestone #1'
author: "Priya Bala and Mihir Pandya"
date: "2023-09-25"
output: pdf_document
---

#### **Please push to GitHub an html document or a PDF (knitted/rendered from an Rmd or Qmd) with the following information  -** 

-   **Project option selection** - Flu Outbreak (simulated) and Vaccine uptake in California - Scenario 1

-   Create git repository

    -   Share a link to your group\'s git repository

    -   <https://github.com/priyabala307/W251_Project.git>

-   Roles and responsibilities

    -   Team's preferred communication method - Text and email

    -   Team's preferred meeting times and frequency - We will meet once a week on zoom to go over project details, time and day might vary with schedule.

    -   Team's preferred method for tracking progress - Creating action items and deadlines after each meeting.

    -   Point person for contacting course facilitators with questions - Priya Bala (pbala307\@berkeley.edu)

#### **Additionally, please do the following:**

-   Ensure each group member has made at least one commit to the repository

-   Add teaching team as collaborators to your repository (instructions on [team project page](https://bcourses.berkeley.edu/courses/1525339/pages/team-project "Team Project"))

------------------------------------------------------------------------

### **Define roles and responsibilities**

#### Meeting Planning

-   What is your team's preferred communication method - email, text, bcourse messaging?

-   When will your team be holding meetings? How frequently will you meet? Are there times or days that work well for everyone?

-   Discuss future non-academic commitments that might affect members' availability.

-   Discuss meeting tempo: \"checking in\" at the beginning of meetings versus \"just sticking to business\".

#### Roles

-   How is your team going to keep track of progress? We will collaborate on agendas and take relevant minutes from the meetings.

-    Who will be taking minutes - We will collaborate, creating agendas - Both of us will work on the agenda, and contacting the course facilitators with questions - Priya Bala (pbala307\@berkeley.edu)?

-   We encourage you to discuss potential dates and times to meet with a course facilitator during Weeks 3-5. Decide on the best date and time for all. **Mondays - 11-4 pm, Wednesday - 1 - 3 pm**

#### Conflict Management

-   If a conflict arises, plan to solve the issue as soon as possible. This is best done using synchronous (Zoom, Google Hangouts) communication rather than asynchronous (email).

-   If the group is unable to resolve the conflict, seek advice from the instructional team. 
